image: gitpod/workspace-java-21
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - pleiades.java-extension-pack-jdk
    - formulahendry.code-runner
    - streetsidesoftware.code-spell-checker
