image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install java-21=tem
    init: |
      echo "📦 Installing jdk 21 tem..."
      sdk install java 21.0.6-tem
      sdk default java 21.0.6-tem
      sdk current
      echo "✅ java 21.0.6 tem is installed"

  - name: List Java Versions
    init: sdk list java | grep installed

  - name: Install direnv
    init: |
      echo "📦 Installing direnv..."
      curl -sfL https://direnv.net/sHELL  | bash
      echo "✅ direnv installed"

  - name: Setup direnv hook for bash
    init: |
      echo "🔌 Adding direnv hook to ~/.bashrc..."
      echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
      source ~/.bashrc
      echo "✅ direnv hook added and sourced"

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - pleiades.java-extension-pack-jdk
    - formulahendry.code-runner
    - streetsidesoftware.code-spell-checker
