image: gitpod/workspace-full

tasks:
  - init: ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run PetClinic app

vscode:
  extensions:
    - vscjava.vscode-java-pack
